name: Linux Meson tests

on:
  push:
    branches:
      - misc_sparse_CI

permissions:
   contents: read  # to fetch code (actions/checkout)

env:
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  INSTALLDIR: "build-install"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  #################################################################################
  linux_32bit:
    name: Linux - 32 bit
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'dschult/scipy' || github.repository == '')
    runs-on: ubuntu-latest
    # I tried running directly in a container:, using the image: and options:
    # entries. Unfortunately at this time options: does not seem to listen to
    # --platform linux/i386.
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - name: build + test
      run: |
        set -euo pipefail
        docker pull quay.io/pypa/manylinux2014_i686
        docker run -v $(pwd):/scipy --platform=linux/i386 quay.io/pypa/manylinux2014_i686 /bin/bash -c "cd /scipy && \
        uname -a && \
        basedir=\$(python3.9 tools/openblas_support.py) && \
        cp -r \$basedir/lib/* /usr/local/lib && \
        cp \$basedir/include/* /usr/local/include && \
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig && \
        python3.9 -m venv test && \
        source test/bin/activate && \
        python -m pip install doit click rich_click pydevtool meson ninja && \
        python -m pip install numpy==1.22.4 cython pybind11 pytest pytest-timeout pytest-xdist pytest-env 'Pillow<10.0.0' mpmath pythran pooch meson hypothesis && \
        LD_LIBRARY_PATH=/usr/local/lib python dev.py build && \
        LD_LIBRARY_PATH=/usr/local/lib python dev.py test -t scipy/sparse/tests/test_coo.py::test_idx_dtype_tocsr_csc"
